version: '3.4'
services:

  nats:
    image: 'nats:latest'
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    deploy:
      replicas: 1

  broker-overlay-multiplexer:
    image: 'matei10/nats-overlay-brokers:${IMG_NEW_TAG}'
    environment:
      - MODE=broker-m
      - REDIS_PASSWORD=Passw0rd
      - REDIS_HOST=redis-master
      - NATS_SERVERS=nats://nats:4222
    deploy:
      replicas: 1

  broker-overlay-sbscription-manager:
    image: 'matei10/nats-overlay-brokers:${IMG_NEW_TAG}'
    environment:
      - MODE=broker-sm
      - REDIS_PASSWORD=Passw0rd
      - REDIS_HOST=redis-master
      - NATS_SERVERS=nats://nats:4222
    deploy:
      replicas: 1

  subscriber:
    image: 'matei10/nats-overlay-brokers:${IMG_NEW_TAG}'
    environment:
      - MODE=subscriber
      - REDIS_PASSWORD=Passw0rd
      - REDIS_HOST=redis-master
      - NATS_SERVERS=nats://nats:4222
    deploy:
      replicas: 0

  publisher:
    image: 'matei10/nats-overlay-brokers:${IMG_NEW_TAG}'
    environment:
      - MODE=publisher
      - REDIS_PASSWORD=Passw0rd
      - REDIS_HOST=redis-master
      - NATS_SERVERS=nats://nats:4222
    deploy:
      replicas: 0

  determinist-subscriber:
    image: 'matei10/nats-overlay-brokers:${IMG_NEW_TAG}'
    environment:
      - MODE=determinist-subscriber
      - REDIS_PASSWORD=Passw0rd
      - REDIS_HOST=redis-master
      - NATS_SERVERS=nats://nats:4222
    deploy:
      replicas: 1

  determinist-publisher:
    image: 'matei10/nats-overlay-brokers:${IMG_NEW_TAG}'
    environment:
      - MODE=determinist-publisher
      - REDIS_PASSWORD=Passw0rd
      - REDIS_HOST=redis-master
      - NATS_SERVERS=nats://nats:4222
    deploy:
      replicas: 1

  snitch:
    image: 'matei10/nats-overlay-brokers:${IMG_NEW_TAG}'
    environment:
      - MODE=snitch
      - REDIS_PASSWORD=Passw0rd
      - REDIS_HOST=redis-master
      - NATS_SERVERS=nats://nats:4222
    deploy:
      replicas: 1

  pollution:
    image: 'matei10/nats-overlay-brokers:${IMG_NEW_TAG}'
    environment:
      - MODE=pollution
      - REDIS_PASSWORD=Passw0rd
      - REDIS_HOST=redis-master
      - NATS_SERVERS=nats://nats:4222
    deploy:
      replicas: 1

  redis-master:
    image: 'bitnami/redis:5.0.2'
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master 
      - REDIS_PASSWORD=Passw0rd
    # volumes: 
    #   - 'redis:/opt/bitnami/redis/etc/'

volumes:
  redis:
    driver: local
